apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: packet-loss-example
  namespace: chaos-testing
spec:
  action: loss
  mode: all
  selector:
    namespaces:
      - default
  loss:
    loss: "30"
    correlation: "50"
  duration: "2m"

